#! /bin/sh

picom -f &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I III V VII IX
bspc monitor DVI-D-0 -d II IV VI VIII X

bspc config border_width         1
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a conky state=floating border=off
bspc rule -a PyCharm state=floating

# Run polybar
~/.config/polybar/launch.sh --shapes

# Set resolution
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144
xrandr --output DP-0 --mode 2560x1440 --rate 165
xrandr --output DP-0 --primary --left-of DVI-D-0

# Disable mouse acceleration
xset m 1/1 0
xinput --set-prop 19 'libinput Accel Speed' -1

# Set background
feh --bg-fill ~/Documents/background.jpg

# Fix cursor not showing on desktop (background)
lxappearance &
lxpolkit &
sleep 3
killall lxappearance
