#! /bin/sh

# start picom with config
picom --experimental-backend --config ~/.config/picom.conf &

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

bspc monitor DP-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          8
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

bspc rule -a Chromium		desktop='^3'	follow=on
bspc rule -a Waterfox		desktop='^3'	follow=on
bspc rule -a discord		desktop='^6'	follow=off
bspc rule -a Thunar 		desktop='^7'	follow=on
bspc rule -a Lxappearance	desktop='^10'	follow=off
bspc rule -a Brave-browser	desktop='^3'	follow=on
bspc rule -a kitty			desktop='^1'	follow=on
bspc rule -a KeePassXC		desktop='^8'	follow=on
bspc rule -a Shutter		desktop='^9' 	follow=on
bspc rule -a Lutris			desktop='^4'	follow=on
bspc rule -a Postman		desktop='^9'	follow=on
bspc rule -a Notepadqq		desktop='^2' 	follow=on
bspc rule -a xfce-settings	desktop='^10'	follow=on # doesn't work (for some reason)
bspc rule -a Gimp			desktop='^5'	follow=on	state=floating # doesn't work (for some reason)
bspc rule -a Grub-customizer desktop='^10' 	follow=on
bspc rule -a Peazip			desktop='^7'	follow=on
bspc rule -a BleachBit 		desktop='^10'	follow=on
bspc rule -a gnome-calculator desktop='^9'	follow=on
bspc rule -a Clementine		desktop='^5'	follow=on
bspc rule -a Haruna			desktop='^5'	follow=on # doesn't work (for some reason)
bspc rule -a code-oss 		desktop='^2' 	follow=on
bspc rule -a easyeffects	desktop='^10' 	follow=on
bspc rule -a GParted		desktop='^10'	follow=on
bspc rule -a kdenlive		desktop='^5'	follow=on
bspc rule -a obs			desktop='^5'	follow=on
bspc rule -a DesktopEditors	desktop='^9'	follow=on
bspc rule -a Pavucontrol	desktop='^10'	follow=on
bspc rule -a Nvidia-settings desktop='^10'	follow=on
bspc rule -a Ristretto		desktop='^5'	follow=on
bspc rule -a Steam			desktop='^4'	follow=on
bspc rule -a Virt-manager	desktop='^9'	follow=on
bspc rule -a Zoom			desktop='^9'	follow=on # doesn't work (for some reason)
bspc rule -a qBittorrent	desktop='^8' 	follow=on
bspc rule -a obsidian 		desktop='^2' 	follow=on
bspc rule -a NeoVim 		desktop='^2' 	follow=on # Open the NeoVim terminal window done by keybinds super + v on the second desktop
bspc rule -a Sonixd 		desktop='^5' 	follow=on

# Set resolution
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144
xrandr --output DP-0 --mode 2560x1440 --rate 165
xrandr --output DP-0 --primary --left-of DVI-D-0

# Disable mouse acceleration
xset m 1/1 0
xinput --set-prop 8 'libinput Accel Speed' -1

# Set background
feh --bg-fill ~/Documents/background.jpg

# Run polybar
~/.config/polybar/launch.sh

# Auto-Start
bspc desktop -f ^1
lxpolkit & # prompt to enter sudo password daemon
flameshot &
lxappearance & # Fix cursor not showing on desktop (background)
sleep 3
killall lxappearance # Fix cursor not showing on desktop (background)
